name: E2E Tests
run-name:  ${{ github.actor }} is building the app and running E2E tests
on: pull_request
jobs:
  e2e-tests-android:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    outputs:
      apk: android/app/build/outputs/apk/release/app-release.apk

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: npm install -g yarn
      - run: yarn install
      - name: Create .env file
        run: |
          touch .env
          echo API_URL=${{ env.API_URL }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo API_ICON_URL=${{ env.API_ICON_URL }} >> .env
      - run: yarn android:build:release
      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: android/app/build/outputs/apk/release/app-release.apk
  e2e-tests-ios:
    runs-on: macOS-latest
    needs: [continuous-integration]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: npm install -g yarn
      - run: yarn install
      - name: Create .env file
        run: |
          touch .env
          echo API_URL=${{ secrets.API_URL }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo API_ICON_URL=${{ secrets.API_ICON_URL }} >> .env
      - run: yarn ios:build:debug
      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: build/WeatherApp.app
